-- MySQL Script generated by MySQL Workbench
-- Thu Dec 28 16:00:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`joueurs` (
  `Pseudo` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `age` INT NULL,
  `pays` VARCHAR(45) NULL,
  `team` VARCHAR(45) NULL,
  PRIMARY KEY (`Pseudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stats` (
  `stats` INT NOT NULL,
  `kill/rounds` DECIMAL(5,2) NULL,
  `kill/death` DECIMAL(5,2) NULL,
  `dam/round` DECIMAL(5,2) NULL,
  `bonus` DECIMAL(5,2) NULL,
  `malus` DECIMAL(5,2) NULL,
  `total` DECIMAL(5,2) NULL,
  `moyenne` DECIMAL(5,2) NULL,
  `joueurs_Pseudo` INT NOT NULL,
  PRIMARY KEY (`stats`, `joueurs_Pseudo`),
  INDEX `fk_stats_joueurs_idx` (`joueurs_Pseudo` ASC),
  CONSTRAINT `fk_stats_joueurs`
    FOREIGN KEY (`joueurs_Pseudo`)
    REFERENCES `mydb`.`joueurs` (`Pseudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
